### PR TITLE
fix(js): Escape HTML in templates

### LINKED ISSUE #12: When using special characters (", >, <)
The encapsulation for HTML is this:
```html
<span class="tag is-rounded" data-value="email@email.com">
    email@email.com
    <div class="delete is-small" data-tag="delete"></div>
</span>
```
But if we use special characters, for example insert something like: `"Email" <email@email.com>` ... then:
```html
<span class="tag is-rounded" data-value="" Email"="" <email@email.com="">"&gt;
    "Email" <email@email.com>
    <div class="delete is-small" data-tag="delete"></div>
</email@email.com></span>
```
It's completely broken! I think it needs a bit of sanitizing for input.

### PR DESCRIPTION
**Pull request by mieko**
I observed the same issue as #12 in evaluating my usage of bulma-tagsinput.  This PR escapes interpolated JS strings which end up in HTML.

Closes #12

### CODE REVIEW

File: src/js/utils/dom.js [hunk 1]
```diff
@@ -96,4 +96,20 @@ export const cloneAttributes = (target, source, except = null) => {
...
 	});
-}
+};
+
+/**
+ * Escapes string for insertion into HTML, replacing special characters with HTML
+ * entities.
+ * @param {String} string
+ */
+export const escape = (string) => {
```
Comment (mieko) [inline src/js/utils/dom.js:106]: This should be suitable for escaping in the context of text nodes or HTML attributes.

**Review by CreativeBulma — APPROVED** [review]
